#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np


# In[54]:


df_company=pd.DataFrame({'公司':['杭州银行','青农银行','常熟银行','工商银行','上海银行','江苏银行'],
                         '股票代码':['600926','002958','601128','601398','601229','600919'],
                         '市值（亿）':[449,371,237,21313,1369,823],
                         '市盈率':[8.31,15.36,16.01,7.16,7.59,6.3]})


# In[55]:


df_company


# In[56]:


df_company.loc[df_company[u'市值（亿）']<2000]


# In[57]:


df_company.loc[(df_company[u'市值（亿）'] <2000) & (df_company[u'市盈率'] <10)]


# In[62]:


dr=pd.date_range(start='2019-01-02',periods=100)


# In[59]:


data=np.random.randn(100).cumsum()


# In[60]:


close=data-np.min(data)


# In[63]:


df=pd.DataFrame({'close':close},index=dr)


# In[64]:


df


# In[71]:


df.rolling(5).mean()


# In[73]:


df['average_5day']=df.rolling(5).mean()


# In[74]:


df


# In[100]:


df=pd.DataFrame(np.arange(1,17).reshape(4,4), columns=['第1列','第2列','第3列','第4列'],index=['a','b','c','d'])


# In[101]:


df


# In[102]:


df.apply(sum,axis=1)


# In[103]:


df['第5列']=df.apply(lambda x: x[u'第1列']+x[u'第2列'] if x[u'第3列']>10 else x[u'第3列'],axis=1)


# In[104]:


df


# In[ ]:





# In[ ]:




