#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np


# In[37]:


data1=np.random.randint(3,10,size=5)


# In[38]:


data1


# In[39]:


s1=pd.Series(data1,index=['a','b','c','d','e'])


# In[40]:


s1


# In[26]:


s1.loc['c':'e']


# In[28]:


s1.iloc[2:5]


# In[41]:


df=pd.DataFrame({'year':[17,2018,2019],'price':[10,20,30]})


# In[42]:


df


# In[43]:


data2=np.random.randint(5,15,size=(5,3))


# In[44]:


data2


# In[65]:


df_test=pd.DataFrame(data2,index=['a','c','e','f','h'],
                     columns=['one','two','three'])


# In[66]:


df_test


# In[67]:


df_test.loc['a','one']=np.nan


# In[68]:


df_test.loc['c','two']=-99


# In[69]:


df_test.loc['a','two']=-100


# In[70]:


df_test['four']='test'


# In[71]:


index_new=['a','b','c','d','e','f','g','h']


# In[72]:


df_test.reindex(index_new)


# In[ ]:




