#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np


# In[2]:


arr1=np.random.randn(4).reshape(2,2)


# In[3]:


arr1


# In[4]:


arr2=np.zeros(36).reshape(6,6)


# In[5]:


arr2


# In[6]:


arr3=np.ones(36).reshape(6,6)


# In[7]:


arr3


# In[8]:


arr4=np.identity(6)


# In[9]:


arr4


# In[14]:


arr5=np.arange(0,10,2)


# In[15]:


arr5


# In[18]:


arr6=np.linspace(2,12,num=6,dtype=int)


# In[19]:


arr6


# In[39]:


arr7=np.random.randint(10,size=10)
arr7[np.argmax(arr7)]=0


# In[40]:


arr7


# In[41]:


x=np.array([1,2,3,2,3,4,3,4,5,6])


# In[43]:


y=np.array([7,2,10,2,7,4,9,4,9,8])


# In[52]:


dist1=np.linalg.norm(x-y)


# In[53]:


dist1


# In[58]:


import matplotlib.pyplot as plt 

np.random.seed(1)
values=np.random.randn(1000).cumsum()
plt.plot(values,color='steelblue')
plt.show()


# In[60]:


max_drawdown=np.max(np.maximum.accumulate(values)-values)


# In[61]:


max_drawdown

