#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np


# In[2]:


id=['1001','1001','1002','1003','1001','1002','1002','1003','1001','1002','1001','1002']


# In[4]:


date=['2019-01-01','2019-01-01','2019-01-01','2019-01-01',
      '2019-01-02','2019-01-02','2019-01-01','2019-01-02',
      '2019-01-03','2019-01-03','2019-01-04','2019-01-04']


# In[6]:


goods=['A','B','A','B','A','A','B','A','A','B','A','A']


# In[8]:


sales=[3000, 2000, 3000, 2000, 3000, 3000, 2000, 3000, 3000, 2000, 3000, 3000]


# In[10]:


df1=pd.DataFrame({'id':id,'date':date,'goods':goods,'sales':sales})


# In[11]:


df1


# In[36]:


df2=pd.pivot_table(df1,index=['id','goods'],values=['sales'],columns=['date'],aggfunc=np.sum,fill_value=0)


# In[37]:


df2


# In[39]:


df3=pd.pivot_table(df1,index=['id'],values=['sales'],columns=['date'],aggfunc=np.sum,fill_value=0, margins=True)


# In[40]:


df3


# In[41]:


sex=['man','man','women','women','man','women','man','women','women']


# In[42]:


age=[15,23,25,17,35,57,24,31,22]


# In[50]:


smoke=[True,False,False,True,True,False,False,True,False]


# In[44]:


height=[168,179,181,166,173,178,188,190,160]


# In[51]:


df_a=pd.DataFrame({'sex':sex,'age':age,'smoke':smoke,'height':height})


# In[52]:


df_a


# In[54]:


df_1b=pd.pivot_table(df_a,index=['sex'],values=['age','height'], columns=['smoke'],aggfunc=np.mean,fill_value=0)


# In[55]:


df_1b


# In[70]:


result1=pd.crosstab(index=df_a['sex'],columns=df_a['smoke'],margins=True)


# In[71]:


result1


# In[74]:


result2=pd.crosstab(index=df_a['age'],columns=df_a['smoke'],margins=True)


# In[75]:


result2


# In[ ]:




