#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np


# In[2]:


df=pd.read_csv(r'C:\Users\yili3\OneDrive\Desktop\sh.600000.csv',encoding='utf-8')


# In[3]:


df.head()


# In[4]:


df.tail()


# In[6]:


df.describe()


# In[8]:


df.index


# In[9]:


df.columns


# In[10]:


df.index.names


# In[11]:


df.values


# In[12]:


df[:3]


# In[13]:


type(df['date'])


# In[15]:


type(df[['date','open','close']])


# In[16]:


df.where(df['close']>11.08)


# In[18]:


df.index=df['date']


# In[20]:


df1=df


# In[22]:


df1.loc['2017-12-11':'2017-12-20']


# In[23]:


df1.loc['open':'close']


# In[28]:


df.loc['2018-07-01':'2018-07-08','open':'close']


# In[ ]:




